[param]
interface_type = "Uart"
comport_uart = "COM10"
speed_uart = "2000000"
speed_jlink = "1000"
bl60x_brd = "IoTKitA"
bl60x_xtal = "40M"
aes_key = ""
aes_iv = ""
addr = "0x0"

[check_box]
partition_download = true
boot2_download = true
bin_download = true
media_download = false
use_romfs = false
mfg_download = false
ro_params_download = true
ckb_erase_all = "False"
encrypt = false
download_single = false

[input_path]
pt_bin_input = "C:\\Users\\divad\\Documents\\!FLASHED!\\BL602\\BLDC1.4.8\\bl602\\partition\\partition_cfg_2M.toml"
boot2_bin_input = "C:\\Users\\divad\\Documents\\!FLASHED!\\BL602\\BLDC1.4.8\\bl602\\builtin_imgs\\blsp_boot2.bin"
cfg2_bin_input = "C:\\Users\\divad\\Downloads\\OpenBL602_1.17.509.bin"
meida_bin_input = ""
romfs_dir_input = ""
mfg_bin_input = ""
img_bin_input = ""
